### ISSUE TITLE
Make a new release to solve issues that have already been fixed

### ISSUE THREAD

**Issue by jjatria** [Perl-Toolchain-Gang/File-Temp#26]
I ran into [RT #60340](https://rt.cpan.org/Public/Bug/Display.html?id=60340) while trying to install Dist::Zilla on a machine running Windows 10. That issue, which was marked as "important" back in 2010 when it was first opened (!), was fixed in 2016 when #10 was merged.

However, File::Temp has not had a new release since 2013.

Please consider making a new release, if only to fix this one issue, whose solution appears to be available since 2016.

**Comment by karenetheridge** [comment]
Looks like TJENNESS has the sole maint bit on this module... another core
distribution with bus factor 1 :(

\#oslo

**Comment by timj** [comment]
2013 was when I had to leave Perl behind. I thought I'd given someone her co-maint on CPAN. Let me know if someone wants to do a release.

**Comment by timj** [comment]
Can @xdg do it?

**Comment by karenetheridge** [comment]
@timj I'd be happy to take comaint (ETHER on pause); I'm sure xdg would be willing as well (cpan:DAGOLDEN). It might be a good idea to also add P5P, which is held by the Perl Pumpking (currently SawyerX). The more the merrier! :)

**Comment by jjatria** [comment]
Any updates on this? Asking for a friend. :slightly_smiling_face:

**Comment by karenetheridge** [comment]
We will still be blocked on either 1. Tim Jenness making a release, or 2.
passing on comaint to one or more volunteers. *waves to Tim*

**Comment by xdg** [comment]
We have a few PAUSE admins around. :-) @timj any objection to me giving co-maint to ETHER?

**Comment by timj** [comment]
I've added ETHER and DAGOLDEN. I'm very sorry about this. I don't understand how I didn't make @xdg co-maint back when he first took over File::Temp.

**Comment by Leont** [comment]
@timj++

**Comment by karenetheridge** [comment]
​No worries! I'll look at the queued patches and tickets over the next few
days at the Toolchain Summit and get out a release.

**Comment by karenetheridge** [comment]
This ticket is now resolved with File-Temp-0.2305-TRIAL. Please let me know how it works out and I will make a stable release soon.

**Comment by jjatria** [comment]
Sorry, I didn't have access to Windows until now to test it. The new release installs successfully. Thank you!

**Comment by rivy** [comment]
@karenetheridge , @xdg 

While you're looking back into this module, I've got an AppVeyor config/script that I'd like to contribute that'll allow drop-in testing of most modules for Win32 back to perl version 5.8.8, as well as adding code coverage.

I have a near-complete first version that I'm testing on various modules before pushing it out into the wild. If you're amenable, I'll submit a PR (here and a couple of other places) likely over the next weekend.
